
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: roboshop
  labels: # these labels are deployment labels
    app: web
    project: roboshop
    tier: web
spec:
  replicas: 1
  selector:
    matchLabels: # these labels are used to find the pods
      app: web
      project: roboshop
      tier: web
  template:
    metadata:
      labels: # these labels are pod labels
        app: web
        project: roboshop
        tier: web
    spec:
      containers:
      - name: web
        image: chsusmi/web:v1
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: roboshop
spec:
  type: LoadBalancer
  selector:
    app: web
    project: roboshop
    tier: web
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 80  